server:
  port: 8762
spring:
  application:
    name: nativerconfigserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
